CREATE DATABASE SCHOOLTRANSPORT;

USE SCHOOLTRANSPORT;

CREATE TABLE ROUTE (
    RouteID VARCHAR(5) PRIMARY KEY,
    RouteName VARCHAR(40),
    DistanceKm DECIMAL(5,2)
);

CREATE TABLE STOP (
    StopID VARCHAR(5) PRIMARY KEY,
    StopName VARCHAR(50),
    RouteID VARCHAR(5),
    DistanceKm DECIMAL(5,2),
    TransportFee DECIMAL(8,2),
    FOREIGN KEY (RouteID) REFERENCES ROUTE(RouteID)
);

CREATE TABLE BUS (
    BusNo VARCHAR(5) PRIMARY KEY,
    DriverName VARCHAR(50),
    Capacity INT,
    RouteID VARCHAR(5),
    FOREIGN KEY (RouteID) REFERENCES ROUTE(RouteID)
);

CREATE TABLE STUDENT (
    StudentID VARCHAR(8) PRIMARY KEY,
    StudentName VARCHAR(50),
    ClassNo INT,
    Section CHAR(1),
    BusNo VARCHAR(5),
    RouteID VARCHAR(5),
    StopID VARCHAR(5),
    FeeStatus VARCHAR(10),
    FOREIGN KEY (BusNo) REFERENCES BUS(BusNo),
    FOREIGN KEY (RouteID) REFERENCES ROUTE(RouteID),
    FOREIGN KEY (StopID) REFERENCES STOP(StopID)
);
