CREATE DATABASE SCHOOLTRANSPORT;

USE SCHOOLTRANSPORT;

CREATE TABLE ROUTE (
    RouteID VARCHAR(5) PRIMARY KEY,
    RouteName VARCHAR(40),
    DistanceKm DECIMAL(5,2)
);

CREATE TABLE STOP (
    StopID VARCHAR(5) PRIMARY KEY,
    StopName VARCHAR(50),
    RouteID VARCHAR(5),
    DistanceKm DECIMAL(5,2),
    TransportFee DECIMAL(8,2),
    FOREIGN KEY (RouteID) REFERENCES ROUTE(RouteID)
);

CREATE TABLE BUS (
    BusNo VARCHAR(5) PRIMARY KEY,
    DriverName VARCHAR(50),
    Capacity INT,
    RouteID VARCHAR(5),
    FOREIGN KEY (RouteID) REFERENCES ROUTE(RouteID)
);

CREATE TABLE STUDENT (
    StudentID VARCHAR(8) PRIMARY KEY,
    StudentName VARCHAR(50),
    ClassNo INT,
    Section CHAR(1),
    BusNo VARCHAR(5),
    RouteID VARCHAR(5),
    StopID VARCHAR(5),
    FeeStatus VARCHAR(10),
    FOREIGN KEY (BusNo) REFERENCES BUS(BusNo),
    FOREIGN KEY (RouteID) REFERENCES ROUTE(RouteID),
    FOREIGN KEY (StopID) REFERENCES STOP(StopID)
);

CREATE TABLE BUS_STATUS (
    BusNo VARCHAR(5) PRIMARY KEY,
    CurrentStopID VARCHAR(5),
    TripStatus VARCHAR(20),
    LastUpdateTime TIME,
    FOREIGN KEY (BusNo) REFERENCES BUS(BusNo),
    FOREIGN KEY (CurrentStopID) REFERENCES STOP(StopID)
);

CREATE TABLE TRIP_LOG (
    LogID VARCHAR(8) PRIMARY KEY,
    StudentID VARCHAR(8),
    BusNo VARCHAR(5),
    TripDate DATE,
    CheckInTime TIME,
    CheckOutTime TIME,
    TripStatus VARCHAR(20),
    FOREIGN KEY (StudentID) REFERENCES STUDENT(StudentID),
    FOREIGN KEY (BusNo) REFERENCES BUS(BusNo)
);

CREATE TABLE NOTIFICATION (
    NotificationID VARCHAR(8) PRIMARY KEY,
    BusNo VARCHAR(5),
    StudentID VARCHAR(8),
    NotificationType VARCHAR(15),
    Message VARCHAR(120),
    NotificationTime TIME,
    FOREIGN KEY (BusNo) REFERENCES BUS(BusNo),
    FOREIGN KEY (StudentID) REFERENCES STUDENT(StudentID)
);
